const fs = require('fs');
let code = fs.readFileSync('components/chat/GroupFishPickerModal.tsx', 'utf8');
code = code.replace(/style=\{styles\.modalOverlay\}/g, 'className="flex-1 justify-end bg-black/60"');
code = code.replace(/style=\{styles\.modalContent\}/g, 'className="bg-[#1e293b] rounded-t-3xl h-[85%] flex-col"');
code = code.replace(/style=\{styles\.modalHeader\}/g, 'className="flex-row justify-between items-center px-5 pt-5 pb-3 border-b border-[#334155]"');
code = code.replace(/style=\{styles\.modalTitle\}/g, 'className="text-lg font-bold color-[#f8fafc]"');
code = code.replace(/style=\{styles\.modalSubtitle\}/g, 'className="text-xs color-[#94a3b8] mt-1"');
code = code.replace(/style=\{styles\.closeBtn\}/g, 'className="w-9 h-9 items-center justify-center rounded-full bg-[#0f172a]"');
code = code.replace(/style=\{styles\.listContent\}/g, 'className="p-5"');
code = code.replace(/style=\{styles\.fishCard\}/g, 'className="flex-row items-center gap-3 bg-[#0f172a] rounded-xl p-3 border border-[#334155] mb-3"');
code = code.replace(/style=\{styles\.fishCardSelected\}/g, 'className="border-[#3b82f6] bg-[#3b82f6]/10"');
code = code.replace(/style=\{styles\.fishThumb\}/g, 'className="w-[50px] h-[50px] rounded-lg"');
code = code.replace(/style=\{styles\.fishInfo\}/g, 'className="flex-1"');
code = code.replace(/style=\{styles\.fishName\}/g, 'className="text-base font-bold color-[#f8fafc]"');
code = code.replace(/style=\{styles\.fishMeta\}/g, 'className="flex-row items-center gap-2 mt-1"');
code = code.replace(/style=\{styles\.fishMetaText\}/g, 'className="text-[11px] font-semibold color-[#94a3b8]"');
code = code.replace(/style=\{styles\.diseaseTag\}/g, 'className="px-2 py-[2px] rounded-sm bg-[#f87171]/20"');
code = code.replace(/style=\{styles\.diseaseText\}/g, 'className="text-[10px] font-bold color-[#f87171]"');
code = code.replace(/style=\{styles\.actionRow\}/g, 'className="flex-row items-center gap-2 mt-3"');
code = code.replace(/style=\{styles\.actionBtn\}/g, 'className="flex-row items-center gap-1 bg-[#334155] px-3 py-1.5 rounded-lg"');
code = code.replace(/style=\{styles\.actionBtnText\}/g, 'className="text-xs font-semibold color-[#e2e8f0]"');
code = code.replace(/style=\{styles\.confirmBtn\}/g, 'className="bg-[#3b82f6] flex-row items-center justify-center gap-2 py-3.5 mx-5 mb-5 rounded-xl shadow-lg shadow-[#3b82f6]/30"');
code = code.replace(/style=\{styles\.confirmBtnText\}/g, 'className="text-base font-bold color-white"');
fs.writeFileSync('components/chat/GroupFishPickerModal.tsx', code);
