/**
 * PDF Export Utility
 * Exports analysis results to PDF format
 */
import * as Print from "expo-print";
import * as FileSystem from "expo-file-system";
import { Alert, Platform } from "react-native";
import { getAnalysisData } from "./analysis-store";

export async function exportAnalysisToPDF(): Promise<void> {
  const data = getAnalysisData();

  if (!data) {
    Alert.alert("No Data", "No analysis data available to export");
    return;
  }

  try {
    let html = "";

    if (data.mode === "online") {
      const { groupAnalysis, groupId, location } = data;

      html = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Fish Analysis Report</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #3b82f6; }
            h2 { color: #1e293b; margin-top: 20px; }
            table { width: 100%; border-collapse: collapse; margin: 10px 0; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f1f5f9; }
            .header { background-color: #0f172a; color: white; padding: 20px; margin: -20px -20px 20px -20px; }
            .summary { background-color: #f8fafc; padding: 15px; border-radius: 8px; margin: 15px 0; }
            .species-row { display: flex; justify-content: space-between; padding: 5px 0; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🐟 OceanAI Fish Analysis Report</h1>
            <p>Group ID: ${groupId}</p>
            <p>Date: ${new Date(groupAnalysis.processedAt).toLocaleString()}</p>
            ${location ? `<p>Location: ${location.lat.toFixed(5)}°N, ${location.lng.toFixed(5)}°E</p>` : ""}
          </div>

          <div class="summary">
            <h2>Summary Statistics</h2>
            <table>
              <tr><th>Metric</th><th>Value</th></tr>
              <tr><td>Total Fish Detected</td><td>${groupAnalysis.aggregateStats.totalFishCount}</td></tr>
              <tr><td>Average Confidence</td><td>${(groupAnalysis.aggregateStats.averageConfidence * 100).toFixed(1)}%</td></tr>
              <tr><td>Total Weight</td><td>${groupAnalysis.aggregateStats.totalEstimatedWeight.toFixed(2)} kg</td></tr>
              <tr><td>Total Value</td><td>₹${groupAnalysis.aggregateStats.totalEstimatedValue.toLocaleString("en-IN")}</td></tr>
              <tr><td>Disease Status</td><td>${groupAnalysis.aggregateStats.diseaseDetected ? "⚠️ Disease Detected" : "✅ All Healthy"}</td></tr>
            </table>
          </div>

          <h2>Species Distribution</h2>
          <table>
            <tr><th>Species</th><th>Count</th></tr>
            ${Object.entries(groupAnalysis.aggregateStats.speciesDistribution)
              .sort(([, a], [, b]) => b - a)
              .map(
                ([species, count]) =>
                  `<tr><td>${species}</td><td>${count}</td></tr>`,
              )
              .join("")}
          </table>

          <h2>Per-Image Details</h2>
          ${groupAnalysis.images
            .map(
              (img, idx) => `
            <div style="margin: 20px 0; padding: 15px; background: #f8fafc; border-radius: 8px;">
              <h3>Image ${idx + 1}</h3>
              <p>Fish detected: ${Object.keys(img.crops).length}</p>
              ${img.error ? `<p style="color: red;">Error: ${img.error}</p>` : ""}
            </div>
          `,
            )
            .join("")}

          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e2e8f0; text-align: center; color: #64748b;">
            <p>Generated by OceanAI - AI for Bharat Challenge</p>
            <p>AWS AI for Bharat Challenge</p>
          </div>
        </body>
        </html>
      `;
    } else {
      // Offline mode
      const { offlineResults, processingTime, location } = data;
      const totalFish = offlineResults.length;
      const totalWeightKg =
        offlineResults.reduce((s, d) => s + d.weightG, 0) / 1000;
      const totalValue = offlineResults.reduce(
        (s, d) => s + d.estimatedValue,
        0,
      );
      const speciesDist = offlineResults.reduce<Record<string, number>>(
        (acc, d) => {
          acc[d.species] = (acc[d.species] || 0) + 1;
          return acc;
        },
        {},
      );

      html = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Fish Analysis Report (Offline)</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #3b82f6; }
            h2 { color: #1e293b; margin-top: 20px; }
            table { width: 100%; border-collapse: collapse; margin: 10px 0; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f1f5f9; }
            .header { background-color: #0f172a; color: white; padding: 20px; margin: -20px -20px 20px -20px; }
            .summary { background-color: #f8fafc; padding: 15px; border-radius: 8px; margin: 15px 0; }
            .offline-badge { background: #10b981; color: white; padding: 5px 10px; border-radius: 5px; display: inline-block; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🐟 OceanAI Fish Analysis Report</h1>
            <p><span class="offline-badge">Offline Mode (On-Device)</span></p>
            <p>Date: ${new Date().toLocaleString()}</p>
            <p>Processing Time: ${processingTime}ms</p>
            ${location ? `<p>Location: ${location.lat.toFixed(5)}°N, ${location.lng.toFixed(5)}°E</p>` : ""}
          </div>

          <div class="summary">
            <h2>Summary Statistics</h2>
            <table>
              <tr><th>Metric</th><th>Value</th></tr>
              <tr><td>Total Fish Detected</td><td>${totalFish}</td></tr>
              <tr><td>Total Weight</td><td>${totalWeightKg.toFixed(2)} kg</td></tr>
              <tr><td>Total Value</td><td>₹${totalValue.toLocaleString("en-IN")}</td></tr>
            </table>
          </div>

          <h2>Species Distribution</h2>
          <table>
            <tr><th>Species</th><th>Count</th></tr>
            ${Object.entries(speciesDist)
              .sort(([, a], [, b]) => b - a)
              .map(
                ([species, count]) =>
                  `<tr><td>${species}</td><td>${count}</td></tr>`,
              )
              .join("")}
          </table>

          <h2>Individual Fish Details</h2>
          <table>
            <tr>
              <th>#</th>
              <th>Species</th>
              <th>Weight</th>
              <th>Length</th>
              <th>Health</th>
              <th>Quality</th>
              <th>Value</th>
            </tr>
            ${offlineResults
              .map(
                (det, idx) => `
              <tr>
                <td>${idx + 1}</td>
                <td>${det.species}</td>
                <td>${(det.weightG / 1000).toFixed(2)} kg</td>
                <td>${det.lengthMm} mm</td>
                <td>${det.disease}</td>
                <td>${det.qualityGrade}</td>
                <td>₹${det.estimatedValue}</td>
              </tr>
            `,
              )
              .join("")}
          </table>

          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e2e8f0; text-align: center; color: #64748b;">
            <p>Generated by OceanAI - AI for Bharat Challenge</p>
            <p>AWS AI for Bharat Challenge</p>
          </div>
        </body>
        </html>
      `;
    }

    // Generate PDF
    const { uri } = await Print.printToFileAsync({ html });

    // Save to downloads directory
    const fileName = `OceanAI_Report_${Date.now()}.pdf`;
    const docDir = (FileSystem as any).documentDirectory || "";
    const downloadPath = `${docDir}${fileName}`;

    try {
      await FileSystem.copyAsync({
        from: uri,
        to: downloadPath,
      });

      Alert.alert(
        "PDF Exported",
        `Report saved successfully!\n\nLocation: ${downloadPath}`,
        [{ text: "OK", style: "default" }],
      );
    } catch (copyError) {
      // Fallback: just show the temp URI
      Alert.alert(
        "PDF Generated",
        `Report created at: ${uri}\n\nYou can find it in your file manager.`,
        [{ text: "OK" }],
      );
    }
  } catch (error) {
    console.error("PDF export error:", error);
    throw error;
  }
}
